In [1]:
import numpy as np

In [2]:
import array

In [3]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [6]:
type(np.array([1,2,3,4,5, "ved", 5+7j,]))

numpy.ndarray

In [7]:
np.array([1,2.3,4.5,4,5,6])

array([1. , 2.3, 4.5, 4. , 5. , 6. ])

In [9]:
np.array([[1,3],[3,4]])

array([[1, 3],
       [3, 4]])

In [10]:
np.array([[[1,3],[3,4]],[[1,3],[3,4]]])

array([[[1, 3],
        [3, 4]],

       [[1, 3],
        [3, 4]]])

In [11]:
np.array([1,2,3], dtype = complex)

array([1.+0.j, 2.+0.j, 3.+0.j])

In [33]:
arr = np.array([[1,3],[3,4]], dtype = [("a",'<i2'),("b",'<i8')])

In [34]:
arr

array([[(1, 1), (3, 3)],
       [(3, 3), (4, 4)]], dtype=[('a', '<i2'), ('b', '<i8')])

In [47]:
arr = np.array([[1,3],[3,4]])

In [48]:
type(arr[0][0])

numpy.int32

In [49]:
type(arr[0][1])

numpy.int32

In [50]:
mat = np.matrix(arr)

In [51]:
l = [1,2,3,4,5,6,6]

In [52]:
np.array(l)

array([1, 2, 3, 4, 5, 6, 6])

In [53]:
np.asarray(l)

array([1, 2, 3, 4, 5, 6, 6])

In [54]:
np.asanyarray(mat)

matrix([[1, 3],
        [3, 4]])

In [55]:
np.asarray(mat)

array([[1, 3],
       [3, 4]])

In [56]:
issubclass(np.matrix, np.ndarray)

True

In [57]:
issubclass(np.ndarray, np.matrix)

False

In [58]:
arr

array([[1, 3],
       [3, 4]])

In [60]:
a = arr

In [61]:
b = np.copy(arr)

In [62]:
arr[0][0] = 67

In [63]:
arr

array([[67,  3],
       [ 3,  4]])

In [64]:
b

array([[1, 3],
       [3, 4]])

In [65]:
a

array([[67,  3],
       [ 3,  4]])

In [66]:
np.fromfunction(lambda i , j : i==j, (4,4))

array([[ True, False, False, False],
       [False,  True, False, False],
       [False, False,  True, False],
       [False, False, False,  True]])

In [67]:
np.fromfunction(lambda i,j : i*j, (3,3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])